server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        native:
          search-locations: classpath:config/licensingservice
encrypt:
  key: secret